// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Users.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserName");

                    b.ToTable("Users", "app");

                    b.HasDiscriminator<string>("Type").HasValue("UserEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Users.Entities.AdminEntity", b =>
                {
                    b.HasBaseType("Domain.Users.Entities.UserEntity");

                    b.HasDiscriminator().HasValue("admin");
                });

            modelBuilder.Entity("Domain.Users.Entities.RegularUserEntity", b =>
                {
                    b.HasBaseType("Domain.Users.Entities.UserEntity");

                    b.HasDiscriminator().HasValue("regular");
                });

            modelBuilder.Entity("Domain.Users.Entities.UserEntity", b =>
                {
                    b.OwnsOne("Domain.Common.Audit.DeletionAudit", "DeletionInfo", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long>("DeletedById")
                                .HasColumnType("bigint");

                            b1.Property<string>("DeletedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users", "app");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.OwnsOne("Domain.Common.Audit.ModificationAudit", "ModificationInfo", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long>("ModifiedById")
                                .HasColumnType("bigint");

                            b1.Property<string>("ModifiedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users", "app");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("DeletionInfo");

                    b.Navigation("ModificationInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
